- pyproject.toml
- src/xiaomi_ble/parser.py
- Adding Petoneer Smart Odor Eliminator Pro (SU001-T)
I don't have an actual bytestring, so no tests
> feat: Petoneer Smart Odor Eliminator Pro (SU001-T)

- src/xiaomi_ble/parser.py
- add lux sensor to cgpr1
- re-added the old light output for future binary light sensor #4
> feat: add lux sensor to cgpr1

- src/xiaomi_ble/parser.py
This PR should either give a lux illuminance output or a binary light output, dependent on the specific device. See #4 which device should give what output.
> device specific light and illuminance output 

- src/xiaomi_ble/parser.py
Support for new Xiaomi lock XMZNMSBMCN03
> Support for new Xiaomi lock XMZNMSBMCN03

- poetry.lock
- pyproject.toml
- src/xiaomi_ble/parser.py
- tests/test_parser.py
Just adds a couple of sensors so can start bootstrapping things in HA.
> feat: intial support for binary_sensor devices

- poetry.lock
- pyproject.toml
related https://github.com/home-assistant/core/issues/78255
> fix: bump bleak-retry-connector

- src/xiaomi_ble/devices.py
- src/xiaomi_ble/parser.py
- tests/test_parser.py
- Add Linptech MS1BB(MI) Door/Window Sensor to the parser. 
- Add Linptech HS1BB(MI) Motion Sensor to the parser. 
Note that motion, opening and button (binary) sensor are not functional in HA yet, as these sensors are not implemented yet. When I have more time, I can look into that, but that will be a different PR.
> feat: add linptech ms1bb and hs1bb

- poetry.lock
fix: unit of measurement formaldehyde
> fix: unit of measurement formaldehyde

- poetry.lock
- pyproject.toml
- src/xiaomi_ble/devices.py
- src/xiaomi_ble/parser.py
- tests/test_parser.py
This PR adds the binary sensors `opening`, `door` and `motion`. 
Along with this sensors, I have added some additional binary sensors with additional information that is being broadcasted, like `knock on the door`, `door left open`, `pry the door`, `door stuck` and `device forcibly removed`. 
In the next comments, I will add some information I have collected about the different sensors, which might be handy for future reference.
> feat: add door opening and motion sensors

- poetry.lock
- pyproject.toml
fix: lower bleak version requirement
> fix: lower bleak version requirement

- src/xiaomi_ble/parser.py
fix: extend binary sensor enums
> fix: extend binary sensor enums

- src/xiaomi_ble/parser.py
- tests/test_parser.py
fix: assign unique keys to device class
> fix: assign unique keys to device class

- src/xiaomi_ble/events.py
- src/xiaomi_ble/parser.py
- tests/test_parser.py
feat: motion events for MUE4094RT
> feat: motion events

- src/xiaomi_ble/parser.py
- tests/test_parser.py
RTCGQ02LM sends a Timeout Motion packet after ~30s of inactivity
Fix #32
> feat(RTCGQ02LM): Implement motion timeout

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- src/xiaomi_ble/parser.py
- tests/test_parser.py
fix: add sleepy_device property
chore: ci fixes and dependencies
> fix: add sleepy_device property

- .github/workflows/ci.yml
chore: bump python semantic release
> chore: bump python semantic release

- src/xiaomi_ble/devices.py
- src/xiaomi_ble/parser.py
- tests/test_parser.py
feat: add support for toothbrushes
The following toothbrushes should be supported with this PR
- M1S-T500
- T700
- T700i
> feat: add support for toothbrushes

- src/xiaomi_ble/parser.py
- tests/test_parser.py
fix: add unit of measurement to counter
> fix: add unit of measurement to counter

- src/xiaomi_ble/devices.py
- src/xiaomi_ble/parser.py
- tests/test_parser.py
fix: use postfix id for double buttons
> fix: use postfix id for double buttons

- src/xiaomi_ble/parser.py
- tests/test_parser.py
feat: add remote buttons
Adding support for 
- remotes 
- YLYK01YL (fix #57)
- YLYK01YL-FANRC
- YLYK01YL-VENFAN
- YLYB01YL-BHFRC
- power binary sensor (on/off)
- WX08ZM Mija Mosquito Repellent (fix #60)
- YM-K1501 Mijia Smart kettle
- V-SK152 Smart Kettle
- low battery binary sensor (low/normal)
> feat: add remote buttons

- src/xiaomi_ble/parser.py
- tests/test_parser.py
fix: postfix plus and min
- HA can't use "+" and "-" in the postfix of an entity
- Add binary power sensor for remote
> fix: postfix plus and min

- src/xiaomi_ble/parser.py
- tests/test_parser.py
fix: proper event_properties formatting
> fix: proper event_properties formatting

- src/xiaomi_ble/devices.py
- src/xiaomi_ble/parser.py
- tests/test_parser.py
feat: add support for MJWSD06MMC
> feat: add support for MJWSD06MMC

- src/xiaomi_ble/devices.py
- src/xiaomi_ble/parser.py
- tests/test_parser.py
Info: Xiaomi Smart Wireless Switch (2 Gang)
Tests for single, double, and long presses were also added.
> feat: add support for XMWS01XS

- src/xiaomi_ble/devices.py
feat: add support for the xiaomi mbs17 temperature / humidity sensor
> feat: add xiaomi mbs17
