src/xiaomi_ble/parser.py
I wanted to see how many more sensors types I could cover before the beta. Binary sensors aren't going to make it before beta, but we should be able to get most of the other sensors.
I have questions about a few, though.
* obj1014 - we label this as moisture, but according to iot.mi.com its flood detection. i'm guessing this is a binary sensor?
* obj1018 - "Light intensity" - is this lux?
Are there any other "easy" ones I could add to this PR? I think the rest are either definitely binary sensors or fairly complicated and i'm not sure if want to add them without more test data or an actual device to test with.
=> Add rest of (non binary) sensors

poetry.lock, pyproject.toml, src/xiaomi_ble/const.py, src/xiaomi_ble/parser.py
See #10. This adds 2 new methods that will be called be a new API in Home Assistant - `ActiveDataProcessor` - which will check the battery on a MiFlora once a day, or the first time we see a MiFlor after 24 hours.
=> feat: support polling MiFlora battery

src/xiaomi_ble/devices.py
- fix: rename smart door lock e device type to xmznms04lm
- fix: rename linptech k9b to switch
=> Rename Smart Door Lock E

poetry.lock, pyproject.toml, src/xiaomi_ble/const.py, src/xiaomi_ble/parser.py, tests/test_parser.py
See https://github.com/home-assistant/home-assistant.io/pull/24365.
Todo:
I'll try and finish this tomorrow.
=> feat: add support for HHCCJCY10

pyproject.toml
pyproject.toml file wasn't updated with latest sensor-state-data version
fix: bump sensor-state-data to 2.12.1
=> fix: bump sensor-state-data

src/xiaomi_ble/devices.py, src/xiaomi_ble/parser.py
- Add support for Xiaomi Mijia Smart Temperature and Humidity Monitor 3 (MJWSD05MMC)
- Add support for Xiaomi Wireless Switch (Bluetooth) (XMWXKG01LM)
- Add support for Linptech K9BB wall switch (battery powered, 1 button version)
Note. The last two won't really work yet, as the button switch sensor isn't implemented yet. But with this PR, we have the info ready when we are going to add the button switches.
=> feat: add new xiaomi sensors

src/xiaomi_ble/devices.py, tests/test_parser.py
fix: jtyjgd03mmi was detected as temperature sensor, but is a smoke detector. This PR fixes this issue (fix #45)
=> fix: jtyjgd03mmi is now detected as smoke sensor

poetry.lock, pyproject.toml, src/xiaomi_ble/parser.py, tests/test_parser.py
fix: use only kg for mass
As requested by @emontnemery in https://github.com/home-assistant/core/pull/96807, I'm going to forward MiScale data only in kg, and I will use the Mass sensor for stabilized mass/weight. So I only need the non-stabilized mass sensor type.
=> fix: use only kg for mass

poetry.lock, pyproject.toml
fix: remove some dependencies
I have addidently added some dependencies in the last PR, which makes the PR https://github.com/home-assistant/core/pull/96967 fail due to conflicting dependency versions. Hopefully, this will fix it.
=> fix: remove some dependencies

src/xiaomi_ble/parser.py
Starting with Python 3.12 `datetime.utcfromtimestamp` will be deprecated.
https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcfromtimestamp
/CC @bdraco
=> Replace datetime.utcfromtimestamp

src/xiaomi_ble/parser.py, tests/test_parser.py
feat: add events for single button devices
- Adding events for the following single button devices
- XMWXKG01LM
- K9BB-1BTN
- RTCGQ02LM
- YLAI003
- JTYJGD03MI
- SJWS01LM
Other button devices- and other events will follow in different PR's, I first want to have the event entity working in HA for motion detected and (most) buttons with one button.
=> feat: add events for single button devices

src/xiaomi_ble/parser.py, tests/test_parser.py
feat: add button devices with multiple buttons
Adding support for the following button devices
- K9B-1BTN (one button)
- K9B-2BTN (two buttons)
- K9B-3BTN (three buttons)
- MS1BB(MI) (one button)
- XMWXKG01YL (two buttons)
=> feat: add button devices with multiple buttons

src/xiaomi_ble/events.py, src/xiaomi_ble/parser.py, tests/test_parser.py
feat: add dimmer and rubiks cube events
This PR adds support for the following devices. 
- XMMF01JQD (rubiks cube)
- YLKG07YL/YLKG08YL (dimmer) Fix #25
=> feat: add dimmer and rubiks cube events

src/xiaomi_ble/events.py, src/xiaomi_ble/parser.py, tests/test_parser.py
fix: rename rubiks_cube to cube
HA is splitting up events based on the underscore, which should not be done for the rubiks cube
=> fix: rename rubiks_cube to cube

src/xiaomi_ble/locks.py
=> fix: typo in lock events

src/xiaomi_ble/parser.py, tests/test_parser.py
I noticed when using the esphome ble proxies for humidity data from LYWSD03MMC sensors, the values would stair step up in .1% increments until .9, then fall back to .0. I did not see this behavior when using the native esphome support for these sensors.   In the bluetooth channel in the HA discord,  Jc2k recalled that the ble_monitor custom component handled this but it was not ported over.  With that in mind I found references to code that worked around this behavior in the ble_monitor custom component and the native esphome sensor for these devices.  I've noted the links as comments in the code.
The ble_monitor code accounted for firmware version but I didn't see how to reference firmware version in the parser.py.
I'm happy to adjust but may need some help.
=> fix: handle jagged stairstep for LYWSD03MMC humidity

src/xiaomi_ble/devices.py, src/xiaomi_ble/parser.py, tests/test_parser.py
feat: add ptx and xmpiro2sx
Add Xiaomi Human Body Sensor 2S (XMPIRO2SXS)
Add Xiaomi PTX wireless switch (PTX)
Fix for Xiaomi Button (XMWXKG01LM)
=> feat: add ptx and xmpiro2sx

src/xiaomi_ble/parser.py, tests/test_parser.py
feat: allow one failed decryption before reauth
this PR should fix https://github.com/home-assistant/core/issues/113833
=> feat: allow one failed decryption before reauth

src/xiaomi_ble/devices.py, src/xiaomi_ble/parser.py, tests/test_parser.py
Attempt to add support for RS1BB(MI) in [xiaomi-ble](https://github.com/Bluetooth-Devices/xiaomi-ble).
I'm not sure what is the best way to test this change, but I try to raise the PR anyway and will try to explore how to test it out.
This PR is based on the change made in ble_monitor by @Ernst79: https://github.com/custom-components/ble_monitor/pull/1300/commits/2b5e8ea496d543ec5100fcd4c0e34bc7942a299f
=> feat: add support for Linptech RS1BB(MI)

src/xiaomi_ble/parser.py
Now using the same mechanism for fetching the battery level of GCLS002 (device id 0x03BC) that was already in place for HHCCJCY01 (device id 0x0098).
Tested locally:
closes #78
=> feat: extend HHCCJCY01 battery level reading to GCLS002

src/xiaomi_ble/const.py, src/xiaomi_ble/devices.py, src/xiaomi_ble/parser.py, tests/test_parser.py
feat: support 2024 new battery based xiaomi mijia occupancy(human presence) sensor (XMOSB01XS)
New test cases are added.
Also the change is verified by Home Assistant (with a small additional change in xiaomi-ble component for additional new properties)
Hardware Info:
- https://www.aliexpress.com/i/1005007104780534.html
- https://www.mi.com/shop/buy/detail?product_id=19994
=> feat: support xiaomi occupancy(human presence) sensor (XMOSB01XS)

src/xiaomi_ble/devices.py, tests/test_parser.py
this battery device is really a sleepy device.
it won't broadcast any occupancy message unless it is changed.
=> fix: add xmosb01xs as a sleepy device

src/xiaomi_ble/devices.py
It's actually the same as the China mainland version (XMPIR02SXS vs XMPIR02SGXS).
The only change is the device id as the code change indicates.
The change is manually verified by Home Assistant (no change except using the new xiaomi-ble package)
Hardware Info:
- https://www.mi.com/global/product/xiaomi-motion-sensor-2s/
=> feat: support xiaomi motion sensor 2s - global version (XMPIR02SGXS)

src/xiaomi_ble/const.py, src/xiaomi_ble/devices.py, src/xiaomi_ble/parser.py, tests/test_parser.py
Add support for Xiaomi [Body Composition Scale S400](https://www.mi.com/global/product/xiaomi-body-composition-scale-s400/specs/) (MJTZC01YM), this fixes https://github.com/Bluetooth-Devices/xiaomi-ble/issues/158.
=> feat: support Body Composition Scale S400 (MJTZC01YM)

src/xiaomi_ble/devices.py, tests/test_parser.py
This PR adds support for the Linptech ES3 human presence sensor, a radar-based occupancy sensor that's functionally identical to the Xiaomi XMOSB01XS but manufactured by Linptech.
- **Device ID**: 0x50FB
- **Model**: ES3
- **Manufacturer**: Linptech
- **Type**: Human presence sensor
- **Features**: Occupancy detection, illuminance measurement
- **Encryption**: MiBeacon V5 encrypted
- Added ES3 to `DEVICE_TYPES` dictionary in `src/xiaomi_ble/devices.py`
- Added ES3 to `SLEEPY_DEVICE_MODELS` set (battery-powered, event-based broadcasting)
- Added 3 new tests covering:
- Illuminance data parsing (173 lux)
- Occupancy detected state
- Occupancy cleared state
The ES3 implementation is based on the existing support in the [ble_monitor](https://github.com/custom-components/ble_monitor) custom …
=> feat: add support for Linptech ES3 human presence sensor
